services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    container_name: postgres_db

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: django_container
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py loaddata data.json &&
                    python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db