# Generated by Django 5.0.6 on 2024-06-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.DecimalField(decimal_places=0, max_digits=1)),
                ('description', models.TextField(null=True)),
                ('in_format', models.TextField(null=True)),
                ('out_format', models.TextField(null=True)),
                ('type_name', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.TextField(null=True)),
                ('outputs', models.TextField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Problem.question')),
            ],
        ),
    ]
